# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Categories: /categories
  Tags: /tags

# Logo Image Source
logo_src: /img/logo.svg

# Theme Main Subtitle
subtitle_main: Welcome to my personal blog!

# Theme Secondary subtitle
susbtitle_secondary: I am Hyeonseok Jung and interested in programming

# Footer About Section
about_footer: <a href="https://github.com/klugjo/hexo-theme-phantom/">Phantom</a> theme

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: james0248
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-158967608-1

# Social Accounts
facebook_url: https://www.facebook.com/profile.php?id=100010033112069
github_url: https://github.com/james0248
email_url: hsjames0248@gmail.com
rss_url: \#